# Generated by Django 4.2.3 on 2023-08-07 06:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mixed_Physique",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("physique", models.CharField(max_length=255)),
                (
                    "single_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "single_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.ImageField(upload_to="pictures/")),
            ],
        ),
        migrations.CreateModel(
            name="Single_Physique",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("physique", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TongueFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("TC", "舌色"),
                            ("MC", "苔色"),
                            ("MQ", "苔质"),
                            ("TS", "舌形"),
                            ("BF", "津液"),
                            ("SC", "舌下络脉"),
                        ],
                        default="TC",
                        max_length=2,
                    ),
                ),
                ("specific_feature", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tagged_Data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "physique_type",
                    models.CharField(max_length=255, verbose_name="体质类型"),
                ),
                (
                    "tongue_shape_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="舌形",
                    ),
                ),
                (
                    "single_physique_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "physique_id",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "body_fluid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_fluid",
                        to="annotation.tonguefeature",
                        verbose_name="津液",
                    ),
                ),
                (
                    "moss_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moss_color",
                        to="annotation.tonguefeature",
                        verbose_name="苔色",
                    ),
                ),
                (
                    "moss_quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moss_quality",
                        to="annotation.tonguefeature",
                        verbose_name="苔质",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_data",
                        to="annotation.picture",
                        verbose_name="图片",
                    ),
                ),
                (
                    "sublingual_collaterals",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublingual_collaterals",
                        to="annotation.tonguefeature",
                        verbose_name="舌下络脉",
                    ),
                ),
                (
                    "tongue_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tongue_color",
                        to="annotation.tonguefeature",
                        verbose_name="舌色",
                    ),
                ),
            ],
        ),
    ]
